//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sökö_laskuri.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sökö_laskuri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_2e6810bdef979c5572285928cfdd6879 {
            get {
                object obj = ResourceManager.GetObject("2-2e6810bdef979c5572285928cfdd6879", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_2e6810bdef979c5572285928cfdd68791 {
            get {
                object obj = ResourceManager.GetObject("2-2e6810bdef979c5572285928cfdd68791", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_39418f7c31cedc5d4e676813120d48d5 {
            get {
                object obj = ResourceManager.GetObject("2-39418f7c31cedc5d4e676813120d48d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_3a9ce70c43049219e1fb113b944a4b52 {
            get {
                object obj = ResourceManager.GetObject("2-3a9ce70c43049219e1fb113b944a4b52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_c07dff9f866a3c7dccdc0b90918bb583 {
            get {
                object obj = ResourceManager.GetObject("2-c07dff9f866a3c7dccdc0b90918bb583", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_358a5ccaa0bce1fb4922cc59646e8688 {
            get {
                object obj = ResourceManager.GetObject("3-358a5ccaa0bce1fb4922cc59646e8688", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_4d8f531fa398c6528dc6a0e0674a00e4 {
            get {
                object obj = ResourceManager.GetObject("3-4d8f531fa398c6528dc6a0e0674a00e4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_9bb8ec1304eb5fb3312f475c5de29b45 {
            get {
                object obj = ResourceManager.GetObject("3-9bb8ec1304eb5fb3312f475c5de29b45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_e088d25fb2cf1377233f09d93d5a4712 {
            get {
                object obj = ResourceManager.GetObject("3-e088d25fb2cf1377233f09d93d5a4712", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_18ee35b6f559ccb8a9733989c219e22e {
            get {
                object obj = ResourceManager.GetObject("4-18ee35b6f559ccb8a9733989c219e22e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_5713175c2625725ffd01ed75eb2f9a37 {
            get {
                object obj = ResourceManager.GetObject("4-5713175c2625725ffd01ed75eb2f9a37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_bd9c25d6bd948331b645f261914bee31 {
            get {
                object obj = ResourceManager.GetObject("4-bd9c25d6bd948331b645f261914bee31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_dd762d285d0d7a816565c3e1a54887a0 {
            get {
                object obj = ResourceManager.GetObject("4-dd762d285d0d7a816565c3e1a54887a0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_409cb091d7e78524f457c47453621e0b {
            get {
                object obj = ResourceManager.GetObject("5-409cb091d7e78524f457c47453621e0b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_5e8e3e67a4181a306e7e689ec6659858 {
            get {
                object obj = ResourceManager.GetObject("5-5e8e3e67a4181a306e7e689ec6659858", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_795d32aa626d7bcc5915bc735536f0ee {
            get {
                object obj = ResourceManager.GetObject("5-795d32aa626d7bcc5915bc735536f0ee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_cc221abc62dd896f281171f909473d92 {
            get {
                object obj = ResourceManager.GetObject("5-cc221abc62dd896f281171f909473d92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_8433587a9010fde9fea3f29e431b3413 {
            get {
                object obj = ResourceManager.GetObject("6-8433587a9010fde9fea3f29e431b3413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_b4b8865fd75ed4ecd4360e73c70de537 {
            get {
                object obj = ResourceManager.GetObject("6-b4b8865fd75ed4ecd4360e73c70de537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_ec8836e3292031f99ba9d4049e15d83e {
            get {
                object obj = ResourceManager.GetObject("6-ec8836e3292031f99ba9d4049e15d83e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_fc30006807b97c2bd9a77fa5308a0da2 {
            get {
                object obj = ResourceManager.GetObject("6-fc30006807b97c2bd9a77fa5308a0da2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_22269186558dfb327a391b56e0516b2f {
            get {
                object obj = ResourceManager.GetObject("7-22269186558dfb327a391b56e0516b2f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_34cbc0aad8b9ab57160625299892101f {
            get {
                object obj = ResourceManager.GetObject("7-34cbc0aad8b9ab57160625299892101f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_59582b248b29ce0ec0e6ccc18a73356f {
            get {
                object obj = ResourceManager.GetObject("7-59582b248b29ce0ec0e6ccc18a73356f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_6e44256c46c7e0fe50fa08464d1376d8 {
            get {
                object obj = ResourceManager.GetObject("7-6e44256c46c7e0fe50fa08464d1376d8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_2098daff24c3d4f500b4077b581f43f7 {
            get {
                object obj = ResourceManager.GetObject("8-2098daff24c3d4f500b4077b581f43f7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_b8584a6139874112d7e4a6d2facbc2e2 {
            get {
                object obj = ResourceManager.GetObject("8-b8584a6139874112d7e4a6d2facbc2e2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_bb4d5f82d8b72a75cf5851b3163f40c6 {
            get {
                object obj = ResourceManager.GetObject("8-bb4d5f82d8b72a75cf5851b3163f40c6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_d9c46c7826673184793734670dfee92d {
            get {
                object obj = ResourceManager.GetObject("8-d9c46c7826673184793734670dfee92d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_0e00ae2a9d1a99277ab6f59c8741e22a {
            get {
                object obj = ResourceManager.GetObject("9-0e00ae2a9d1a99277ab6f59c8741e22a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_44cd08aea0f02b867c4bf43bff3df9e9 {
            get {
                object obj = ResourceManager.GetObject("9-44cd08aea0f02b867c4bf43bff3df9e9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_72d48c18490adb38af9a8583ffc480b1 {
            get {
                object obj = ResourceManager.GetObject("9-72d48c18490adb38af9a8583ffc480b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_a5f892d32ffae38a22738ae1687b6844 {
            get {
                object obj = ResourceManager.GetObject("9-a5f892d32ffae38a22738ae1687b6844", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_11c73136d0af53baf0b1cf04c31d016e {
            get {
                object obj = ResourceManager.GetObject("A-11c73136d0af53baf0b1cf04c31d016e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_2cc1611190e49d0efef6b87f54cbf401 {
            get {
                object obj = ResourceManager.GetObject("A-2cc1611190e49d0efef6b87f54cbf401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_b5d825abd9516ea9d9a63c93d8f162a6 {
            get {
                object obj = ResourceManager.GetObject("A-b5d825abd9516ea9d9a63c93d8f162a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_bf9398d7a9a124f5001c7ad3cd02ed19 {
            get {
                object obj = ResourceManager.GetObject("A-bf9398d7a9a124f5001c7ad3cd02ed19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_side_design_playing_cards_260nw_647735683 {
            get {
                object obj = ResourceManager.GetObject("back-side-design-playing-cards-260nw-647735683", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J_29ead4601e8cfc2d79768214f84669ef {
            get {
                object obj = ResourceManager.GetObject("J-29ead4601e8cfc2d79768214f84669ef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J_4ee080652416226f2c6d08cfaab3c54b {
            get {
                object obj = ResourceManager.GetObject("J-4ee080652416226f2c6d08cfaab3c54b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J_852e042c517e09a92486ce213423fc11 {
            get {
                object obj = ResourceManager.GetObject("J-852e042c517e09a92486ce213423fc11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J_8796f258313daf8acdddf8cb88e951e7 {
            get {
                object obj = ResourceManager.GetObject("J-8796f258313daf8acdddf8cb88e951e7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap K_1937a84a0020eef4aba9eecc475342f0 {
            get {
                object obj = ResourceManager.GetObject("K-1937a84a0020eef4aba9eecc475342f0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap K_219b2176328afbd044a53908f815d0b9 {
            get {
                object obj = ResourceManager.GetObject("K-219b2176328afbd044a53908f815d0b9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap K_5c366fb22daf149e4539fc7b006e20db {
            get {
                object obj = ResourceManager.GetObject("K-5c366fb22daf149e4539fc7b006e20db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap K_d19ab44b124bb26202fd7907ec06b74e {
            get {
                object obj = ResourceManager.GetObject("K-d19ab44b124bb26202fd7907ec06b74e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Q_20989fca1c17a3545d6343a3390d245f {
            get {
                object obj = ResourceManager.GetObject("Q-20989fca1c17a3545d6343a3390d245f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Q_7a16fd60816d5663e6f4b71bb981eb7d {
            get {
                object obj = ResourceManager.GetObject("Q-7a16fd60816d5663e6f4b71bb981eb7d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Q_7b0af4160c80c45cf6b3aa76951eecd2 {
            get {
                object obj = ResourceManager.GetObject("Q-7b0af4160c80c45cf6b3aa76951eecd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Q_abd69f807ca7fef209b5712b76107abb {
            get {
                object obj = ResourceManager.GetObject("Q-abd69f807ca7fef209b5712b76107abb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_8918b02e07d19324bcd62d32afe83c61 {
            get {
                object obj = ResourceManager.GetObject("T-8918b02e07d19324bcd62d32afe83c61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_a7c47c3ab1be0c2e5c00cfab8d4371bd {
            get {
                object obj = ResourceManager.GetObject("T-a7c47c3ab1be0c2e5c00cfab8d4371bd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_a956b31d64ee2a7392744d7a87959f71 {
            get {
                object obj = ResourceManager.GetObject("T-a956b31d64ee2a7392744d7a87959f71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_acfaa38639aaa07d30ad03a8b25cc740 {
            get {
                object obj = ResourceManager.GetObject("T-acfaa38639aaa07d30ad03a8b25cc740", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
